## START: Set by rpmautospec
## (rpmautospec version 0.8.4)
## RPMAUTOSPEC: autorelease, autochangelog
%define autorelease(e:s:pb:n) %{?-p:0.}%{lua:
    release_number = 7;
    base_release_number = tonumber(rpm.expand("%{?-b*}%{!?-b:1}"));
    print(release_number + base_release_number - 1);
}%{?-e:.%{-e*}}%{?-s:.%{-s*}}%{!?-n:%{?dist}}
## END: Set by rpmautospec

%global glib2_version 2.79.0
%global gtk4_version 4.15.0
%global libadwaita_version 1.6~beta
%global blueprint_compiler_version 0.18

Name:           showtime
Version:        50.0

Release:        %autorelease
Summary:        Modern video player built using GTK4

License:        GPL-3.0-or-later
URL:            https://apps.gnome.org/Showtime/
Source0:        https://download.gnome.org/sources/%{name}/%{gnome_major_version}/%{name}-%{gnome_tarball_version}.tar.xz

%gnome_check_version

BuildArch:      noarch

BuildRequires:  desktop-file-utils
BuildRequires:  gcc
BuildRequires:  gettext
BuildRequires:  meson
BuildRequires:  blueprint-compiler >= %{blueprint_compiler_version}
BuildRequires:  python3-devel
BuildRequires:  pkgconfig(glib-2.0) >= %{glib2_version}
BuildRequires:  pkgconfig(gnome-desktop-4)
BuildRequires:  pkgconfig(gtk4) >= %{gtk4_version}
BuildRequires:  pkgconfig(libadwaita-1) >= %{libadwaita_version}
BuildRequires:  desktop-file-utils
BuildRequires:  libappstream-glib

Requires:       gtk4 >= %{gtk4_version}
Requires:       libadwaita >= %{libadwaita_version}
Requires:       python3
Requires:       hicolor-icon-theme
Requires:       gstreamer1-plugins-base
Requires:       gstreamer1-plugin-gtk4
Requires:       (gstreamer1-plugin-openh264 if openh264)

Recommends:     gstreamer1-plugins-good
Recommends:     gstreamer1-plugins-bad-free
Recommends:     gstreamer1-plugins-ugly-free

%description
Play your favorite movies and video files without hassle. Showtime
features simple playback controls that fade out of your way when
you're watching, fullscreen, adjustable playback speed, multiple
language and subtitle tracks, and screenshots — everything you
need for a straightforward viewing experience.

%prep
%autosetup -p1 -n %{name}-%{gnome_tarball_version}

%build
%meson
%meson_build

%install
%meson_install
%find_lang %{name}

%check
appstream-util validate-relax --nonet %{buildroot}%{_metainfodir}/org.gnome.Showtime.metainfo.xml
desktop-file-validate $RPM_BUILD_ROOT%{_datadir}/applications/*.desktop

%files  -f %{name}.lang
%doc README.md
%license COPYING
%{python3_sitelib}/showtime/
%{_bindir}/showtime
%{_datadir}/applications/org.gnome.Showtime.desktop
%{_datadir}/dbus-1/services/org.gnome.Showtime.service
%{_datadir}/glib-2.0/schemas/org.gnome.Showtime.gschema.xml
%{_datadir}/icons/hicolor/scalable/apps/org.gnome.Showtime.svg
%{_datadir}/icons/hicolor/symbolic/apps/org.gnome.Showtime-symbolic.svg
%{_metainfodir}/org.gnome.Showtime.metainfo.xml
%{_datadir}/showtime/

%changelog
## START: Generated by rpmautospec
* Fri Jul 17 2026 Fedora Release Engineering <releng@fedoraproject.org> - 50.0-7
- Rebuilt for https://fedoraproject.org/wiki/Fedora_45_Mass_Rebuild

* Tue Jun 30 2026 Milan Crha <mcrha@redhat.com> - 50.0-6
- Rebuild for new gnome-desktop4

* Wed Jun 03 2026 Python Maint <python-maint@redhat.com> - 50.0-4
- Rebuilt for Python 3.15

* Wed Mar 25 2026 Jan Grulich <jgrulich@redhat.com> - 50.0-3
- Add configuration for release-monitoring

* Mon Mar 16 2026 Milan Crha <mcrha@redhat.com> - 50.0-1
- Update to 50.0

* Tue Mar 03 2026 Jan Grulich <jgrulich@redhat.com> - 50~rc-1
- Update to 50.rc

* Mon Mar 02 2026 Jan Grulich <jgrulich@redhat.com> - 50~beta-4
- Packit: drop upstream_project_url and rely on release-monitoring only

* Wed Feb 25 2026 Jan Grulich <jgrulich@redhat.com> - 50~beta-3
- Packit: drop fast_forward_merge_into as current stable branches diverge

* Tue Feb 24 2026 Jan Grulich <jgrulich@redhat.com> - 50~beta-2
- Onboard to Packit for stable Fedora branches

* Tue Feb 03 2026 Jan Horak <jhorak@redhat.com> - 50~beta-1
- Update to 50.beta

* Sat Jan 17 2026 Fedora Release Engineering <releng@fedoraproject.org> - 49.1-2
- Rebuilt for https://fedoraproject.org/wiki/Fedora_44_Mass_Rebuild

* Wed Dec 10 2025 Adrian Vovk <adrianvovk@gmail.com> - 49.1-1
- Update to 49.1

* Fri Sep 19 2025 Python Maint <python-maint@redhat.com> - 49.0-2
- Rebuilt for Python 3.14.0rc3 bytecode

* Tue Sep 16 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 49.0-1
- Update to 49.0

* Thu Sep 04 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 49~rc-1
- Update to 49.rc

* Fri Aug 15 2025 Python Maint <python-maint@redhat.com> - 49~beta-2
- Rebuilt for Python 3.14.0rc2 bytecode

* Tue Aug 05 2025 nmontero <nmontero@redhat.com> - 49~beta-1
- Update to 49~beta

* Fri Jul 25 2025 Fedora Release Engineering <releng@fedoraproject.org> - 49~alpha-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_43_Mass_Rebuild

* Mon Jul 07 2025 Milan Crha <mcrha@redhat.com> - 49~alpha-2
- Specify blueprint-compiler version requirement

* Mon Jun 30 2025 Milan Crha <mcrha@redhat.com> - 49~alpha-1
- Update to 49.alpha

* Tue Jun 03 2025 Python Maint <python-maint@redhat.com> - 48.1-2
- Rebuilt for Python 3.14

* Mon May 05 2025 nmontero <nmontero@redhat.com> - 48.1-1
- Update to 48.1

* Tue Mar 11 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 48.0~20250201.beta.1-4
- Add FIXME and warning comment regarding package version

* Tue Mar 11 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 48.0~20250201.beta.1-3
- Add GStreamer plugins Requires/Recommends

* Tue Mar 11 2025 Michael Catanzaro <mcatanzaro@redhat.com> - 48.0~20250201.beta.1-2
- Convert to rpm-autospec

* Sat Feb 22 2025 Steve Cossette <farchord@gmail.com> - 48.0~20250201.beta.1-1
- Update to 48.beta.1

* Sun Jan 19 2025 Fedora Release Engineering <releng@fedoraproject.org> - 48.0~20241104.080500.5579430-3
- Rebuilt for https://fedoraproject.org/wiki/Fedora_42_Mass_Rebuild

* Tue Jan 07 2025 Neal Gompa <ngompa@fedoraproject.org> - 48.0~20241104.080500.5579430-2
- Make the package noarch

* Wed Nov 13 2024 Steve Cossette <farchord@gmail.com> - 48.0~20241104.080500.5579430-1
- Initial import (fedora#2324442).
## END: Generated by rpmautospec
